name: Docker Kivy APK Build

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t kivy-apk-builder .

      - name: Run Buildozer inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app kivy-apk-builder ./build.sh

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: grocery-app-apk
          path: ./bin/*.apk
